name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install VS Code Dev Containers CLI
        run: npm install -g vs-dev-containers-cli
      - name: Build and push Docker image
        env:
          CONTAINER_IMAGE: httpvsgrpc/devenv
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          vsdc build --image $CONTAINER_IMAGE --auth $DOCKER_USERNAME:$DOCKER_PASSWORD
          vsdc push --image $CONTAINER_IMAGE --auth $DOCKER_USERNAME:$DOCKER_PASSWORD
